### ISSUE TITLE
Wrong FC info

### ISSUE THREAD

**Issue by Dsuable** [ChirpyMisha/FullComboPercentageCounter#2]
Mod's FC is different from my FC. There is almost always a difference minimal or huge.

![a](https://user-images.githubusercontent.com/106661588/186515739-69e17628-fe29-400a-a66b-cc526dc76560.jpg)

**Comment by ChirpyMisha** [comment]
Thank you for reminding me to release an update. I have no idea what caused this issue and I have no idea what I did to fix it, but somewhere during debugging it started to work as it should. A couple of people tested the mod and they didn't experience any issues, so I've just released the updated version
